version: '2.1'

services:
  vue-express-app:
    image: vue-express-app
    build:
      # build the from the Dockerfile
      context: .
      args:
        VUE_APP_API: ${VUE_APP_API}
    env_file:
      - .env
    ports:
      - 8000:9000
