version: '2.1'

services:
  heroes-vue-node-api:
    image: vue-express-app
    build:
      context: .
      args:
        VUE_APP_API: ${VUE_APP_API}
    env_file:
      - .env.local
    ports:
      - 8080:9000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 serve.js
