version: '2.1'
# This build is when we want to debug the intenal Node server,
# note that the client Vue app is already production built inside,
# so this is just for the Node server

services:
  vue-express-app-debug:
    image: vue-express-app
    build:
      # build the from the Dockerfile
      context: .
      args:
        VUE_APP_API: api
    env_file:
      - .env.local
    ports:
      - 8080:9000
      - 9229:9229  # expose the node debugger port for debugging externally from VSCode for instance
    command: node --inspect=0.0.0.0:9229 serve.js
