version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    container_name: elasticsearch-mongodb--es
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      # Note !!! if bind-mounting a local directory then it needs proper permissions
      # Elastic runs using uid:gid elasticsearch:elasticsearch (1000:1000)
      # See https://discuss.elastic.co/t/elastic-elasticsearch-docker-not-assigning-permissions-to-data-directory-on-run/65812/2
      # See https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
      - ${PWD}/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.3
    container_name: elasticsearch-mongodb--kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-mongodb--es:9200/
      SERVER_NAME: elasticsearch-mongodb--kibana
      SERVER_BASEPATH: /kibana
      SERVER_REWRITEBASEPATH: 'true'
    ports:
      - 5601:5601
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  mongodb:
    image: mongo:4
    container_name: elasticsearch-mongodb--mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: website
    ports:
      - 27017:27017
    # command: --smallfiles
    volumes:
      # mount the MongoDB data and longs file
      - ${PWD}/mongodb/data:/data
      # initialize the DB - these files in /docker-entrypoint-initdb.d will be executed the first time the container is started
      # this is similat to 'COPY mongodb/initdb.d /docker-entrypoint-initdb.d/' if placed in Dockerfile
      - type: bind
        read_only: true
        source: ${PWD}/mongodb/initdb.d
        target: /docker-entrypoint-initdb.d/

  mongo-express:
    image: mongo-express
    container_name: elasticsearch-mongodb--mongoadmin
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: elasticsearch-mongodb--mongodb
      # ME_CONFIG_MONGODB_ADMINUSERNAME: username
      # ME_CONFIG_MONGODB_ADMINPASSWORD: password
      # set this if MongoExpress is to be accessed behind a reverse-proxy as in the Nginx setup
      ME_CONFIG_SITE_BASEURL: /mongoadmin

  # TODO:
  client:
    image: node:10
    container_name: elasticsearch-mongodb--clientapp
    restart: always
    environment:
      #          mongodb://user:password@hostname:port/defaultDatabase?config
      MONGO_URL: mongodb://elasticsearch-mongodb--mongodb/website
      # set this if the client server app is to be accessed behind a reverse-proxy as in the Nginx setup
      SITE_BASEURL: /client
    expose:
      - 3000

  nginx:
    image: nginx:latest
    container_name: elasticsearch-mongodb--nginx
    ports:
        - 8080:80
    volumes:
        - ${PWD}/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    command: /bin/bash -c "nginx -g 'daemon off;'"
    ulimits:
      nproc: 65535
