version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    container_name: elasticsearch-mongodb--es
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ${PWD}/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.3
    container_name: elasticsearch-mongodb--kibana
    environment:
      SERVER_NAME: elasticsearch-mongodb--kibana
      ELASTICSEARCH_URL: http://elasticsearch-mongodb--es:9200/
    ports:
      - 5601:5601
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  mongodb:
    image: mongo:latest
    container_name: elasticsearch-mongodb--mongodb
    environment:
      MONGO_INITDB_DATABASE: website
    ports:
      - 27017:27017
    # TODO:
    # # initialize the DB
    # COPY mongodb/initdb.d /docker-entrypoint-initdb.d/

  # TODO:
  # client:
  #   image: node:10

  nginx:
    image: nginx:latest
    ports:
        - 8080:80
    volumes:
        - ${PWD}/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    command: /bin/bash -c "nginx -g 'daemon off;'"
    ulimits:
      nproc: 65535
