version: '3.6'
services:
  node:
    image: node:10
    container_name: app
    volumes:
      - ${PWD}/app:/usr/share/app
    working_dir: /usr/share/app
    ports:
      - 3000:3000
    command: node index.js


  nginx:
    image: nginx:latest
    container_name: nginx-app
    ports:
      - 8080:80
    volumes:
      - ${PWD}/nginx:/etc/nginx/conf.d
    command: /bin/bash -c "nginx -g 'daemon off;'"
    ulimits:
      nproc: 65535
