# This docker-compose file will use the Dockerfile(s) of the speficied services/apps to first build them
# because it has "build: ." directive
version: '3.6'
services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=8080
    ports:
      - 8080:8080
